In [3]:
# python program for swapping 

a=int(input("enter your no :"))
b=int(input("enter your no :"))
# befor swapping 
print(a)
print(b)

temp=a #(here temp is 10)
a=b #(here a = 20)
b=temp # (here b = temp ie a)


# after swapping 
print(a)
print(b)

enter your no :10
enter your no :29
10
29
29
10


In [15]:
# program for prime 

no=int(input("enter your no :"))

for i in range(2,no):
    if no%i==0:
        print("Not Prime ")
        break
    else:
        print(" prime")
        break

enter your no :11
 prime


In [25]:
# factorial of no 

no=int(input("enter your no :"))

fact=1
    
if (no<0):
    print("it's a negative no , factorial not exist")
    
elif (no==0):
    print("factorial is o ")
else:
    for i in range(1,no+1):
        fact=fact*i
    print("Factorial of no is :",fact)
    
    
    

enter your no :8
Factorial of no is : 40320


In [79]:
# sum of all no in range 

a=int(input("enter no :"))

print(sum(range(1,a+1)))

enter no :5
15


In [31]:
# addition of even no from specific range 

no=int(input("enter your range no :"))

sums=0
for i in range(1,no+1):
    if (i%2==0):
        sums+=i
print(sums)
    
        

enter your range no :10
30


In [78]:
# program to remove items that are duplicate in two list 


l1=[1,2,3,4,5]
l2=[4,5,6,7,8]

l3=[]
for i in l1:
    if i in l2:
        l3.append(i)
                      
print(l3)

for i in l3:
    l1.remove(i)
    l2.remove(i)

print(l1)
print(l2)
print(l1+l2)

[4, 5]
[1, 2, 3]
[6, 7, 8]
[1, 2, 3, 6, 7, 8]


In [8]:
# program to sort elements 

ip=[1,3,2,5,4,6,7,10,9,8]

ip.sort(reverse=True)
print(ip)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
# sorting without sort func 



In [77]:
# basic file handling 

f1=open("basic.txt","r+")

f1.write("dfhbehr efjhgerug eghb")

f1.close()

In [109]:
large_array=["sdjhv","wifuiwf","weifyiwgfihwf","divfwdf","egergbihregeirgirehgeg"]

max_len=len(large_array[0])
max_word=large_array[0]


for i in large_array:
    if len(i)>max_len:
        max_len=len(i)
        max_word=i
    else:
        pass
print(max_len)
print(max_word)

22
egergbihregeirgirehgeg


In [1]:
n=int(input("enter your no :"))


def sum1(n):
    flag=False
    sums=0
    while(n>0):
        u=n%10
        n=n//10
        sums=sums+(u*u)
    print(sums)
    if (sums==1):
        print("in if")
        flag=True
    else:
        sum1(sums)
    if flag==True:
        print("Magic")
        
sum1(n)
'''
if (sum1(n)==1):
    print("magic")
else:
    print("not")
'''

enter your no :19
82
68
100
1
in if
Magic


'\nif (sum1(n)==1):\n    print("magic")\nelse:\n    print("not")\n'

In [2]:
n=int(input("enter your no :"))
flag=False
for i in range(10):
    sums=0
    while(n>0):
        u=n%10
        n=n//10
        sums=sums+(u*u)
    n=sums
    print(sums)
    if (sums==1):
        flag=True
        
if(flag==True):
    print("magic")
else:
    print("not magic")
    

enter your no :56
61
37
58
89
145
42
20
4
16
37
not


In [2]:
# numpy (numerical python)(homogenious data )
# faster than lists 
# unlike list , numpy array are of fix size
# faster , more efficient ,less syntax
# one or multi dimensional(size) array 

In [44]:
import numpy as np
list=[1,2,3,4]

# creating array 
sample_array=np.array(list)
tp_array=np.array([5,6,7,8,9])

print(tp_array)
print(sample_array)
print(list)
print(tp_array[1])
print(tp_array[2::])
print(tp_array[2::-1])
print(tp_array[0:3:2])
print(tp_array[-1:-3:-1])


for i in tp_array:
    print(i)

[5 6 7 8 9]
[1 2 3 4]
[1, 2, 3, 4]
6
[7 8 9]
[7 6 5]
[5 7]
[9 8]
5
6
7
8
9


In [5]:
# 2-d array (row,column) also called as matrix 
# can define as array of an array


import numpy as np

arr=np.array([[1,2,3],[4,5,6],[3,4,5]])
# [1,2,3]=row1
#[4,5,6]=row2

print(arr)
#print(sum(arr[0]))


for i in arr:
    print(sum(i))

b=np.transpose(arr)
print(b)

for i in b:
    print(sum(i))

[[1 2 3]
 [4 5 6]
 [3 4 5]]
6
15
12
[[1 4 3]
 [2 5 4]
 [3 6 5]]
8
11
14


In [77]:
import numpy as np

arr=np.array([1,3,4,5,6,7,8,9,9])

print(arr[0:])
print(arr[0:5])
print(arr[0:5:2])
print(arr[-1:-5:-1]) # step count is needed in case of - indexing / slicing 

[1 3 4 5 6 7 8 9 9]
[1 3 4 5 6]
[1 4 6]
[9 9 8 7]


In [1]:
# reshaping or shaping of an array 
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[3,4,5]])

arr1=np.array([1,3,4,5,6,7,8,9,9,10,11,12,13,14,15,16,17,18])


print(arr.shape)

#a=arr1.reshape(4,3) # multiplication must be total no of elements 
b=arr1.reshape(2,3,3) # first no is representaing total no of matrix (will form),# second=rows,#column=last

#print(a)

print(b)



(3, 3)
[[[ 1  3  4]
  [ 5  6  7]
  [ 8  9  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [15]:
# hand shaking lamma 
# sum of degree of all vertices is equal to twice the edges 
import numpy as np

d1=int(input("enter degree of vertex v1 :"))


d2=int(input("enter degree of vertex v2 :"))


d3=int(input("enter degree of vertex v3 :"))


d4=int(input("enter degree of vertex v4 :"))

x=np.array([d1,d2,d3,d4])
print(x)
sums=sum(x)
print(sums)

if sums%2!=0:
    print("sums must be even")
else:
    edges=(sums//2)
    print(edges)
    





#list=[d1,d2,d3,d4]
#sums=sum(list)
#print(sums)

enter degree of vertex v1 :2
enter degree of vertex v2 :2
enter degree of vertex v3 :2
enter degree of vertex v4 :1
[2 2 2 1]
7
sums must be even
